version: '3.7'

services:

  project-postgres:
    image: postgres:13.2-alpine
    container_name: project-postgres
    networks:
      - project-network
    restart: "no"
    environment:
      POSTGRES_MULTIPLE_DATABASES: sb-reactive,sb-batch
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - ./docker/postgres:/docker-entrypoint-initdb.d

networks:
  project-network:
